### ISSUE TITLE
How to get (approximate) raw counts?

### ISSUE THREAD

**Issue by gui11aume** [teresho4/scRNA-seq_atlas_Hs_PBMC_aging#1]
Hi! This is an amazing resource! Thank you so much for putting it out there.

I am interested in the raw (unnormalized)  gene counts. I see that you have `nCount_RNA` in the metada, which should allow me to reconstitute approximate counts from the normalized ones. However, I am confused by the text in the [manuscript](https://www.sciencedirect.com/science/article/pii/S1074761323004533?via%3Dihub). It reads

>Filtered matrices were normalized using a scaling factor of 10,000 and centered.

This should produce values of a different order of magnitude, and some (most) of them should be negative because of the centering. Would you explain how the normalized values were computed from the raw counts?

**Comment by teresho4** [comment]
Hello, @gui11aume.
Thank you for your interest in our research. Raw, unnormalized gene counts, could be found here: https://www.synapse.org/#!Synapse:syn50542388. The file name is _raw_counts_h5ad.tar.gz_. So you do not need to reconstitute anything.
Centering in methods refer to ScaleData function step and was performed only on the highly variable genes. I used the 'standart' Seurat pipeline for the data processing, so assay data contains information after LogNormalize function step.

**Comment by gui11aume** [comment]
Thank you so much @teresho4! This is most useful!
